"""Build the complete static site with Python's standard library. Edit content.json, then run python3 build.py."""
from pathlib import Path
import json,html
ROOT=Path(__file__).resolve().parent
OUT=ROOT/'dist'
c=json.loads((ROOT/'content.json').read_text())
esc=lambda value:html.escape(str(value),quote=True)
ig=esc(c['instagram'])
logo='<img class="logo" src="/assets/logo.jpg" alt="Dr.darkChoco" width="325" height="94">'
header=f'''<a class="skip" href="#main">Skip to content</a><header class="header"><div class="container header-inner"><a href="/" aria-label="Dr.darkChoco home">{logo}</a><button class="menu" type="button" aria-expanded="false" aria-controls="main-nav">Menu</button><nav class="nav" id="main-nav" aria-label="Main navigation"><a href="/collection/">Chocolates</a><a href="/collection/?category=seasonal">Gift boxes</a><a href="/about/">Our story</a><a href="/contact/">Find us</a><a class="outline" href="/contact/#inquiry">Inquire</a></nav></div></header>'''
footer=f'''<footer class="footer"><div class="container"><div class="footer-inner"><div class="footer-brand"><a href="/" aria-label="Dr.darkChoco home">{logo}</a><p>Handmade artisan chocolates.<br>A little care in every creation.</p></div><nav aria-label="Footer collection navigation"><a href="/collection/">Explore chocolates</a><a href="/collection/?category=seasonal">Seasonal gift boxes</a><a href="/about/">Our story</a></nav><div><a href="/contact/">Markets &amp; contact</a><a href="/contact/#inquiry">Order inquiries</a><a class="instagram" href="{ig}" target="_blank" rel="noopener noreferrer">Instagram · @dr.darkchoco ↗</a></div></div><small>© Dr.darkChoco · Handmade in small batches</small></div></footer>'''
favicon="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' rx='4' fill='%23231e1a'/%3E%3Ctext x='6' y='25' font-family='Georgia' font-size='26' fill='%23d5b873'%3ED%3C/text%3E%3C/svg%3E"
def page(path,title,description,body):
 target=OUT/path/'index.html';target.parent.mkdir(parents=True,exist_ok=True)
 title=esc(title);description=esc(description)
 target.write_text(f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#231e1a"><title>{title}</title><meta name="description" content="{description}"><meta property="og:title" content="{title}"><meta property="og:description" content="{description}"><meta property="og:type" content="website"><meta property="og:site_name" content="Dr.darkChoco"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="{title}"><meta name="twitter:description" content="{description}"><link rel="icon" type="image/svg+xml" href="{favicon}"><link rel="stylesheet" href="/style.css"><script src="/app.js" defer></script></head><body>{header}<main id="main">{body}</main>{footer}</body></html>''')
def photo(p,sizes='(max-width: 760px) 44vw, 23vw'):
 return f'''<img src="/assets/{p['image']}-640.jpg" srcset="/assets/{p['image']}-640.jpg 640w, /assets/{p['image']}-1440.jpg 1440w" sizes="{sizes}" alt="{esc(p['alt'])}" width="1440" height="1440" loading="lazy" decoding="async">'''
def card(p,home=False):
 dest=f"/collection/?category={p['category']}" if home and p['category']!='seasonal' else f"/products/{p['id']}/"
 badge='<span class="badge">In the spotlight</span>' if p['id']==c['featuredSeason'] else ''
 return f'''<a class="card {'contain' if p['contain'] else ''}" href="{dest}" data-category="{p['category']}"><div class="card-image">{photo(p,'(max-width: 760px) 88vw, 30vw' if p['category']=='seasonal' else '(max-width: 760px) 44vw, 23vw')}</div><h3>{esc(p['name'])}<span class="arrow" aria-hidden="true">→</span></h3><p>{esc(p['caption'])}</p>{badge}</a>'''
hero=f'''<section class="hero"><div class="hero-copy"><p class="eyebrow"><span class="brand-exact">Dr.darkChoco</span> · Handmade chocolates</p><h1>A little art.<br>A moment to savor.</h1><div class="rule"></div><p>Handmade chocolates for thoughtful gifts and everyday moments of delight.</p><a class="button" href="/collection/">Explore chocolates <span aria-hidden="true">→</span></a></div><div class="hero-photo"><img src="/assets/hero-1600.jpg" srcset="/assets/hero-800.jpg 800w, /assets/hero-1600.jpg 1600w" sizes="(max-width: 760px) 100vw, 55vw" alt="Open black Dr.darkChoco box holding all six purple, pink and red lip-shaped chocolates" width="3924" height="3024" fetchpriority="high"></div></section><div class="ribbon"><span>Made in small batches</span><span>Giftable by design</span><a href="{ig}" target="_blank" rel="noopener noreferrer">@dr.darkchoco ↗</a></div>'''
page(Path('.'),'Dr.darkChoco | Handmade artisan chocolates','Explore handmade chocolates, artistic gift boxes and seasonal creations from Dr.darkChoco.',hero+f'''<div class="container"><section class="section" aria-labelledby="explore"><div class="section-head"><div><h2 id="explore">Explore our chocolates</h2><p>Four ways to find something wonderful.</p></div></div><div class="grid">{''.join(card(p,True) for p in c['products'][:4])}</div></section><section class="section" aria-labelledby="seasonal"><div class="section-head"><div><h2 id="seasonal">The seasonal collection</h2><p>Thoughtful chocolate gifts for moments worth celebrating.</p></div><a class="text-link" href="/collection/?category=seasonal">Explore gift boxes →</a></div><div class="grid seasonal">{''.join(card(p,True) for p in c['products'][4:])}</div></section><section class="story-strip"><div><p class="eyebrow">Made with care</p><h2>A personal touch.<br>A small-batch approach.</h2><p>Dr.darkChoco brings together a love of chocolate and an eye for detail. Each handmade creation is a little invitation to slow down, share, and enjoy.</p><a class="text-link" href="/about/">Our story →</a></div><div><p class="eyebrow">Let’s meet</p><h2>For your next<br>beautiful moment.</h2><p>Find market updates or tell us what you have in mind. We would love to hear about your occasion.</p><a class="text-link" href="/contact/">Markets &amp; order inquiries →</a></div></section></div>''')
categories=[('all','All chocolates'),('pralines','Pralines'),('truffles','Truffles'),('tablets','Tablets'),('decorative','Decorative Chocolates'),('seasonal','Seasonal gift boxes')]
buttons=''.join(f'<button class="filter" type="button" data-filter="{key}" aria-pressed="{str(key=="all").lower()}">{name}</button>' for key,name in categories)
page(Path('collection'),'The collection | Dr.darkChoco','Browse pralines, truffles, tablets, decorative chocolates and seasonal gift collections from Dr.darkChoco.',f'''<div class="container"><div class="page-intro"><p class="eyebrow">The collection</p><h1>Find your little delight.</h1><p>Explore our chocolate collections, then get in touch for current options and availability.</p></div><div class="filters" role="group" aria-label="Filter chocolate collections">{buttons}</div><p class="count" id="result-count" role="status" aria-live="polite">7 collections</p><div class="grid catalog">{''.join(card(p) for p in c['products'])}</div><p class="note">Collection photographs show examples of our creations. Please inquire to confirm the current selection, ingredients, sizes and prices.</p><noscript><p>All collections are shown below. Enable JavaScript to use category filters.</p></noscript></div>''')
for p in c['products']:
 facts=''.join(f'<div><dt>{label}</dt><dd>{esc(p[key]) if p.get(key) else "Details to be added — please inquire"}</dd></div>' for key,label in [('size','Size'),('ingredients','Ingredients'),('allergens','Allergens'),('price','Price'),('availability','Availability')])
 page(Path('products')/p['id'],f"{p['name']} | Dr.darkChoco",p['description'],f'''<div class="container"><nav class="breadcrumb" aria-label="Breadcrumb"><a href="/collection/">Collection</a> / {esc(p['name'])}</nav><article class="detail"><div class="detail-photo">{photo(p,'(max-width: 760px) 88vw, 50vw')}</div><div><p class="eyebrow">{'Seasonal gift collection' if p['category']=='seasonal' else 'Handmade chocolates'}</p><h1>{esc(p['name'])}</h1><p>{esc(p['description'])}</p><dl class="facts">{facts}</dl><p class="help">Please confirm ingredients and allergens with us before ordering. The photo is a collection example; current options will be confirmed with your inquiry.</p><a class="button" href="/contact/?product={p['id']}#inquiry">Inquire about {esc(p['name'])} <span aria-hidden="true">→</span></a><p class="help" style="margin-top:15px">An inquiry starts a conversation and does not place an order.</p></div></article><a class="text-link" href="/collection/">← Back to all chocolates</a></div>''')
page(Path('about'),'Our story | Dr.darkChoco','A personal, handmade approach to chocolate. Get to know Dr.darkChoco.',f'''<div class="container"><div class="page-intro"><p class="eyebrow">Our story</p><h1>Chocolate, with a personal touch.</h1></div><section class="split"><div><h2>The joy is in the details.</h2><p>Dr.darkChoco is a personal chocolate brand built around handmade, small-batch creations. Color, shape and a thoughtful presentation are all part of the experience.</p><p>From a small everyday gesture to a gift for a special occasion, the idea is simple: make something that feels personal, and a pleasure to share.</p><p>A fuller story from our maker is coming soon.</p><a class="button" href="/collection/">Explore the collection →</a></div><div class="placeholder"><div>A glimpse behind the chocolate<small>Maker photograph to come</small></div></div></section></div>''')
options='<option value="general">General inquiry</option>'+''.join(f'<option value="{p["id"]}">{esc(p["name"])}</option>' for p in c['products'])
markets=''.join(f'<article class="empty"><h3>{esc(m["name"])}</h3><p>{esc(m["date"])} · {esc(m["time"])}</p><p>{esc(m["address"])}</p></article>' for m in c['markets']) or '<div class="empty"><h3>Upcoming markets</h3><p>No confirmed dates are listed yet. Follow us on Instagram for updates, or ask where to find us next.</p></div>'
page(Path('contact'),'Markets & contact | Dr.darkChoco','Find Dr.darkChoco market updates and prepare an order inquiry to send on Instagram.',f'''<div class="container"><div class="page-intro"><p class="eyebrow">Find us &amp; get in touch</p><h1>A conversation<br>starts something sweet.</h1><p>Have an occasion in mind, or a question about the collection? We would love to hear from you.</p></div><div class="split"><section><h2>Meet us at the market.</h2>{markets}<a class="text-link" href="{ig}" target="_blank" rel="noopener noreferrer">Follow @dr.darkchoco ↗</a><div class="note"><strong>Contact us on Instagram</strong><br>Instagram is our temporary contact route while direct website inquiries are being set up. An Instagram account may be needed to message us.</div></section><section id="inquiry"><h2>Let’s talk chocolate.</h2><p>Prepare your message here, then copy it into an Instagram message to <strong>@dr.darkchoco</strong>. Nothing is sent from this website.</p><form class="form" id="inquiry-form"><label for="name">Your name</label><input id="name" name="name" autocomplete="given-name" maxlength="100" required><label for="product">I’m interested in</label><select id="product" name="product">{options}</select><label for="message">Your message</label><textarea id="message" name="message" minlength="10" maxlength="2000" required placeholder="Tell us about the chocolates, quantity or occasion you have in mind." aria-describedby="message-help"></textarea><p class="help" id="message-help">Please write at least 10 characters. Availability, pricing and order details will be confirmed in conversation. Your draft stays in this page and is not stored.</p><button class="button" type="submit">Prepare message →</button></form><noscript><p>Please contact us directly through the Instagram link below; the message helper needs JavaScript.</p><a class="button" href="{ig}">Open Instagram</a></noscript><div class="output" id="inquiry-output" hidden><h3>Your message is ready to copy.</h3><p class="help">It has not been sent. Copy it, open Instagram, then paste and send it in a message to @dr.darkchoco.</p><label for="inquiry-draft">Message draft</label><textarea id="inquiry-draft" readonly></textarea><div class="actions"><button class="button" id="copy-message" type="button">Copy message</button><a class="button secondary" href="{ig}" target="_blank" rel="noopener noreferrer">Open Instagram ↗</a></div><p class="status" id="copy-status" role="status" aria-live="polite"></p></div></section></div></div>''')
page(Path('404'),'Page not found | Dr.darkChoco','Find your way back to the Dr.darkChoco collection.','<div class="container page-intro"><h1>This page isn’t here.</h1><p>Let’s get you back to the chocolates.</p><a class="button" href="/collection/">Explore the collection</a></div>')
(OUT/'404.html').write_text((OUT/'404/index.html').read_text())
print('Built 12 pages plus 404.html. No external dependencies.')
# Optional: BASE=/repo-name python3 build.py, for hosting under a sub-path (e.g. GitHub Pages project sites).
import os,re
BASE=os.environ.get('BASE','').rstrip('/')
if BASE:
 for f in OUT.rglob('*.html'):
  t=f.read_text()
  t=re.sub(r'\b(href|src)="/(?!/)',lambda m:f'{m[1]}="{BASE}/',t)
  t=re.sub(r'srcset="([^"]*)"',lambda m:'srcset="'+re.sub(r'(^|, )/',lambda n:f'{n[1]}{BASE}/',m[1])+'"',t)
  f.write_text(t)
(OUT/'CNAME').write_text('drdarkchoco.com\n')
